- rebar.config
I had problems with rebar3 when it found two erl_opts. The last erl_opts options is always used.
So, merging the two erl_opts fixes the problem.
> Use only one rebar erl_opts

- src/esockd_proxy_protocol.erl
Set the socket mode to `binary` when *recv* erlang messages from gen_tcp buffer.
> proxy protocol - set to binary socket mode

- .travis.yml
- Makefile
- README.md
- include/esockd.hrl
- src/esockd.app.src
- src/esockd_acceptor.erl
- src/esockd_connection_sup.erl
- src/esockd_listener.erl
- src/esockd_rate_limit.erl
1. Use map to store connection pids instead of process dictionary.
2. Change the format of record definition in some modules.
3. Bump version to 5.4.1
> Improve the design of esockd_connection_sup module

- src/esockd_connection_sup.erl
- src/esockd_udp.erl
Accept the which_children request from the release handler and some other visualization tools.
> fix(connection_sup): mimic supervisor:which_children/1

- src/esockd_limiter.erl
- src/esockd_rate_limit.erl
- test/esockd_limiter_SUITE.erl
- test/esockd_rate_limit_SUITE.erl
1. Add concurrency consuming case for `esockd_limiter`
2. Make more precise pause time for `esockd_rate_limit`
> Enhance Ratelimit checking

- src/esockd.erl
- src/esockd_acceptor.erl
- src/esockd_dtls_acceptor.erl
- src/esockd_limiter.erl
- src/esockd_listener_sup.erl
- src/esockd_rate_limit.erl
- src/esockd_sup.erl
- src/esockd_udp.erl
- test/esockd_SUITE.erl
- test/esockd_limiter_SUITE.erl
- test/esockd_rate_limit_SUITE.erl
**Bugfixes:**
- *esockd_limiter:* not pause on the nonexistent bucket
- *esockd_rate_limit:*  make the pause time more precise
**Features:**
- Add `get/set_manx_conn_rate` for dynamically managing Listener's connection rate
**Incompatible changes:**
- The get/set APIs will throw an error exception if the Listener does not exist
> Release 5.7.2

- src/esockd_proxy_protocol.erl
- test/esockd_proxy_protocol_SUITE.erl
We should handle the failure of receiving proxy info, otherwise, there will be some crash exceptions printed:
In some generic scenarios, LB will keep establishing TCP connections to the server behind to test the live status of the server. In such scenarios, this error log will be printed constantly.
> fix(proxy): avoid crashes in handling proxy protocol

- src/esockd_peercert.erl
```
src/emqx_channel.erl
587
260: Guard test is_binary(Peercert::'nossl' | 'undefined' | esockd_peercert:peercert()) breaks the opaqueness of its argument
588
261: Guard test is_binary(Peercert::'nossl' | 'undefined' | esockd_peercert:peercert()) breaks the opaqueness of its argument
```
> fix(hocon_schema): remove the opaqueness of esockd_peercert:peercert()

- src/esockd.app.src
- src/esockd.appup.src
- src/esockd_transport.erl
- test/esockd_transport_SUITE.erl
A TLS/SSL connection can take up much more RAM than a plain TCP one,
one of the reasons being the certificates being loaded into heap
memory during the handshake.  Running GC immediately after the
handshake can substantially decrease the memory consumption of such
connections.
Connecting 1000 `emqtt-bench` subscribers with SSL.  Computing the difference of results of `erlang:memory()` before and after all clients are connected.
|  | `processes_used` | `total` |
|--|------------------|---------|
| mem increase without gc after handshake (bytes) | `177894208` | `190032440` |
| mem increase with gc after handshake (bytes) | `108428752` | `113740224` |
| `mem(with gc) / mem(without gc)` | `0.662` | `0.728` |
> feat: add option to run gc after TLS/SSL handshake

- src/esockd.appup.src
- src/esockd_transport.erl
After release upgrade from e4.4.3 to e4.4.14, all the new TLS connections will fail to connect to emqx:
```
2023-01-17T12:44:16.319429+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.18564.56>, registered_name: [], error: {function_clause,[{esockd_transport,ssl_upgrade,[#Port<0.435075>,[{ciphers,["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256","TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256","TLS_AES_128_CCM_8_SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384","ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA","ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256","AES256-GCM-SHA384","AES256-SHA256","ECDH …
```
> fix: SSL connection crashes with function_clause error after relup

- .gitignore
- src/esockd.app.src
- src/esockd.appup.src
- src/esockd_proxy_protocol.erl
- test/esockd_proxy_protocol_SUITE.erl
no error log if the socket is closed before any proxy protocol header is received
> fix: do not log error when proxy protocol header is not received

- src/esockd.app.src
- src/esockd.appup.src
- src/esockd_acceptor.erl
- src/esockd_proxy_protocol.erl
- src/esockd_transport.erl
- src/esockd_utils.erl
- test/esockd_proxy_protocol_SUITE.erl
Before the change:
```
2023-04-20T14:56:51.671735+08:00 [error] supervisor: 'esockd_connection_sup - <0.2537.0>', errorContext: connection_shutdown, reason: {invalid_proxy_info,<<"f\n">>}, offender: [{pid,<0.3192.0>},{name,connection},{mfargs,{emqx_connection,start_link,[[{listener_id,<<"mqtt:tcp:external">>},{deflate_options,[]},{max_conn_rate,1000},{active_n,100},{zone,external},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]
2023-04-20T14:57:01.348275+08:00 [error] supervisor: 'esockd_connection_sup - <0.2537.0>', errorContext: connection_shutdown, reason: {proxy_proto_timeout,5000}, offender: [{pid,<0.3194.0>},{name,connection},{mfargs,{emqx_connection,start_link,[[{listener_id,<<"mqtt:tcp:external">>},{deflate_options,[]},{max_conn_rate,1000},{act …
```
> Log error when recv proxy info timeout

- src/esockd.app.src
- src/esockd.appup.src
- src/esockd_proxy_protocol.erl
- test/esockd_proxy_protocol_SUITE.erl
https://emqx.atlassian.net/browse/EMQX-9751
* handle proxy protocol timeout correctly
* handle recv errors while receiving proxy protocol
Should fix https://github.com/emqx/emqx/issues/10488
> Improve receiving proxy protocol information

- src/esockd.appup.src
- src/esockd_connection_sup.erl
- test/echo_server.erl
- test/esockd_connection_sup_SUITE.erl
Lower `ssl_error` shutdown log to `info` level.
Also support `shutdown_count` in shutdown reasons, then log it at `info` level.
For unidentified shutdowns and uncaught exceptions, we continue log at error level.
> 0915 do not log tls at error level

- src/esockd.erl
- src/esockd_connection_sup.erl
- src/esockd_dtls_listener.erl
- src/esockd_listener.erl
- src/esockd_listener_sup.erl
- src/esockd_sup.erl
- src/esockd_udp.erl
- test/const_server.erl
- test/esockd_SUITE.erl
- test/esockd_connection_sup_SUITE.erl
- test/esockd_udp_SUITE.erl
Some listening socket options can not be changed after the socket has been bound (e.g. `backlog`). Before this PR, an attempt to change them is made (i.e. during the call `esockd:set_options/2`) if they were set once during listener setup but haven't changed since then.
Also, pull socket-related options for DTLS listener from `udp_options` property. This ensures that they are not getting into `ssl:handshake/3` later on as before, when they had to be part of `dtls_options` property.
Also, turn `MFA` from argument into an option, and accommodate APIs for that. Make it possible to change it at runtime with the help of `esockd:setopts/2`.
Part of [EMQX-11527](https://emqx.atlassian.net/browse/EMQX-11527).
Part of [EMQX-11528](https://emqx.atlassian.net/browse/EMQX-11528).
> fix(setopts): pass only changed socket options to `setops/2`

- src/esockd.app.src
- src/esockd_acceptor_sup.erl
- test/esockd_SUITE.erl
Porting https://github.com/emqx/esockd/pull/186 to emqx 5.x
> fix: fast fail on invalid ssl options

- include/esockd.hrl
- src/esockd.erl
- src/esockd_acceptor.erl
- src/esockd_connection_sup.erl
- src/esockd_server.erl
- test/esockd_SUITE.erl
- test/esockd_acceptor_SUITE.erl
- Add a validation for `max_connections` config, make sure it's not greater than `ulimit` and `process_llimit`
- Added a new close reason counter group named `closed_max_limit`.
> Check max connections config against ulimit and processes limit

- src/esockd_acceptor_sup.erl
- src/esockd_listener_sup.erl
- test/esockd_SUITE.erl
improves https://github.com/emqx/esockd/pull/191
Previously:
1. if the initial config is invalid, the error message is extremely hard to comprehend because it's a `throw` without context originated from `ssl` lib.
2. if trying to set invalid options, the it's a `badmatch` crash for the caller of `set_options` 
Now:
1. Initial invalid config results with an error with more context `invalid_ssl_option`
2. Invalid options set from `set_options` returns an `{error, Reason}` tuple (with the same context)
see test cases for more details
> refactor: improve ssl options validation

- src/esockd.erl
for OTP build without `poll()` and fallback to `select()`
the first `check_io` result will be primary type `select()`, and the max_fds was 1024.
```erlang
> erlang:system_info(check_io).
[[{name,erts_poll},
{primary,select},
{kernel_poll,false},
{memory_size,13448},
{total_poll_set_size,1},
{lazy_updates,true},
{pending_updates,0},
{batch_updates,false},
{concurrent_updates,false},
{fallback,true},
{max_fds,1024},
{active_fds,0},
{poll_threads,0}],
[{name,erts_poll},
{primary,epoll},
{kernel_poll,epoll},
{memory_size,56},
{total_poll_set_size,5},
{lazy_updates,false},
{pending_updates,0},
{batch_updates,false},
{concurrent_updates,true},
{fallback,false},
{max_fds,1048576},
{active_fds,0},
{poll_threads,0}],
[{name,erts_poll},
{primary,epoll},
{kernel_poll,epoll},
{memory_size,57400}, …
```
> fix: check all results in `erlang:system_info(check_io)`

- src/esockd.erl
- src/esockd_connection_sup.erl
- src/esockd_dtls_listener.erl
- src/esockd_listener.erl
- src/esockd_listener_sup.erl
- test/esockd_SUITE.erl
Meant to be used in situations when `set_options/2` is too dumb: e.g. changing TLS version that in turn renders existing TLS server options incompatible.
See individual commits for details.
> feat: introduce `reset_options/2` facility
